name: Build macOS clang+gfortran

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
    env:
      CC: clang-9
      CXX: clang-9
      FC: gfortran-10

    steps:

    - name: Install basic packages
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        # mpich installs gcc@10 as prerequisite
        brew install automake coreutils gnu-sed llvm@9
        # mpif90 is looking for "gfortran" only
        ln -sf /usr/local/bin/gfortran-10 /usr/local/bin/gfortran

    - name: Checkout
      uses: actions/checkout@v2

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Build NCEPLIBS-external
      run: |
        export PATH="/usr/local/opt/llvm@9/bin:$PATH"
        export LD_LIBRARY_PATH="/usr/local/opt/llvm@9/lib:$LD_LIBRARY_PATH"
        export CPPFLAGS="-I/usr/local/opt/llvm@9/include"
        export LDFLAGS="-L/usr/local/opt/llvm@9/lib -Wl,-rpath,/usr/local/opt/llvm@9/lib"
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=install -DBUILD_MPI=ON
        make -j4
        cat install/modules/esmf/8.0.0
